# Generated by Django 3.0.8 on 2021-09-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
